// @generated
// This file is auto-generated by an internal codegen tool. Do not edit by hand.
#pragma once

namespace vendor_exclusion_fixture
{

int marker()
{
  return 1;
}

} // namespace vendor_exclusion_fixture
