#pragma once
// This module's inner loop was previously bytecode generated by bpftrace and
// imported from pre-compiled BPF programs before we rewrote it by hand.
using namespace std; // SF.7 violation - own code, must not be swallowed by vendor exclusion
class Foo
{
};
